name: pine_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.19.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.5
  pin_code_fields: ^7.4.0
  flutter_staggered_animations: ^1.1.1
  camera: ^0.10.5
  local_auth: ^2.1.6
  simple_gesture_detector: ^0.2.0
  dotted_border: ^2.0.0+3
  file_picker: ^5.3.0
  mime: ^1.0.4
  flutter_downloader: ^1.10.2
  permission_handler: ^10.2.0
  device_info_plus: ^9.0.0
  android_path_provider: ^0.3.0
  provider: ^6.0.5
  dartz: ^0.10.1
  equatable: ^2.0.5
  dio: ^5.1.2
  hooks_riverpod: ^2.3.6
  freezed_annotation:
  json_annotation:
  url_launcher: ^6.1.11
  percent_indicator: ^4.2.3
  google_maps_flutter: ^2.2.6
  image_picker: ^0.8.7+5
  flutter_email_sender: ^5.2.0
  flutter_pdfview: ^1.2.9
  path_provider: ^2.0.15
  sentry_flutter: ^7.5.2
  flutter_hooks: ^0.18.6
dev_dependencies:
  flutter_lints: ^2.0.0
  device_preview: ^1.1.0
  logger: ^1.3.0
  path: ^1.8.3
  intl: ^0.18.0
  fluttertoast: ^8.2.1
  flutter_device_type: ^0.4.0
  google_fonts: ^4.0.4
  flutter_spinkit: ^5.2.0
  get: ^4.6.5
  flutter_native_splash: ^2.2.19
  build_runner:
  freezed:
  json_serializable:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - lib/core/env/
    - lib/core/theme/images/
    - lib/core/theme/icons/
    - lib/core/theme/txts/
    - lib/core/theme/fonts/
    - lib/core/theme/mockups/images/
flutter_intl:
  enabled: true
  arb_dir: lib/core/l10n
flutter_native_splash:
  background_image: lib/core/theme/images/bg_splash.png
  fullscreen: true
  android_12:
    color: "#000000"
