make-model:
	@echo "╠ Make model file in the project..."
	@mason make model -o ../lib/shared/models
make-service:
	@echo "╠ Make service file in the project..."
	@mason make service -o ../lib/shared/services
make-bloc:
	@echo "╠ Make bloc file in the project..."
	@mason make bloc
make-repository:
	@echo "╠ Make repository file in the project..."
	@mason make repository -o ../lib/shared/repository
