final countryJson = {
  "status": "OK",
  "status-code": 200,
  "version": "1.0",
  "access": "public",
  "data": {
    "AD": {"country": "Andorra", "region": "Europe"},
    "AE": {"country": "United Arab Emirates", "region": "Asia"},
    "AF": {"country": "Afghanistan", "region": "Asia"},
    "AG": {"country": "Antigua and Barbuda", "region": "Americas"},
    "AI": {"country": "Anguilla", "region": "Americas"},
    "AL": {"country": "Albania", "region": "Europe"},
    "AM": {"country": "Armenia", "region": "Asia"},
    "AO": {"country": "Angola", "region": "Africa"},
    "AQ": {"country": "Antarctica", "region": ""},
    "AR": {"country": "Argentina", "region": "Americas"},
    "AS": {"country": "American Samoa", "region": "Oceania"},
    "AT": {"country": "Austria", "region": "Europe"},
    "AU": {"country": "Australia", "region": "Oceania"},
    "AW": {"country": "Aruba", "region": "Americas"},
    "AX": {"country": "\u00c5land Islands", "region": "Europe"},
    "AZ": {"country": "Azerbaijan", "region": "Asia"},
    "BA": {"country": "Bosnia and Herzegovina", "region": "Europe"},
    "BB": {"country": "Barbados", "region": "Americas"},
    "BD": {"country": "Bangladesh", "region": "Asia"},
    "BE": {"country": "Belgium", "region": "Europe"},
    "BF": {"country": "Burkina Faso", "region": "Africa"},
    "BG": {"country": "Bulgaria", "region": "Europe"},
    "BH": {"country": "Bahrain", "region": "Asia"},
    "BI": {"country": "Burundi", "region": "Africa"},
    "BJ": {"country": "Benin", "region": "Africa"},
    "BL": {"country": "Saint Barth\u00e9lemy", "region": "Americas"},
    "BM": {"country": "Bermuda", "region": "Americas"},
    "BN": {"country": "Brunei Darussalam", "region": "Asia"},
    "BO": {"country": "Bolivia (Plurinational State of)", "region": "Americas"},
    "BQ": {"country": "Bonaire, Sint Eustatius and Saba", "region": "Americas"},
    "BR": {"country": "Brazil", "region": "Americas"},
    "BS": {"country": "Bahamas", "region": "Americas"},
    "BT": {"country": "Bhutan", "region": "Asia"},
    "BV": {"country": "Bouvet Island", "region": "Americas"},
    "BW": {"country": "Botswana", "region": "Africa"},
    "BY": {"country": "Belarus", "region": "Europe"},
    "BZ": {"country": "Belize", "region": "Americas"},
    "CA": {"country": "Canada", "region": "Americas"},
    "CC": {"country": "Cocos (Keeling) Islands", "region": "Oceania"},
    "CD": {"country": "Congo, Democratic Republic of the", "region": "Africa"},
    "CF": {"country": "Central African Republic", "region": "Africa"},
    "CG": {"country": "Congo", "region": "Africa"},
    "CH": {"country": "Switzerland", "region": "Europe"},
    "CI": {"country": "C\u00f4te d'Ivoire", "region": "Africa"},
    "CK": {"country": "Cook Islands", "region": "Oceania"},
    "CL": {"country": "Chile", "region": "Americas"},
    "CM": {"country": "Cameroon", "region": "Africa"},
    "CN": {"country": "China", "region": "Asia"},
    "CO": {"country": "Colombia", "region": "Americas"},
    "CR": {"country": "Costa Rica", "region": "Americas"},
    "CU": {"country": "Cuba", "region": "Americas"},
    "CV": {"country": "Cabo Verde", "region": "Africa"},
    "CW": {"country": "Cura\u00e7ao", "region": "Americas"},
    "CX": {"country": "Christmas Island", "region": "Oceania"},
    "CY": {"country": "Cyprus", "region": "Asia"},
    "CZ": {"country": "Czechia", "region": "Europe"},
    "DE": {"country": "Germany", "region": "Europe"},
    "DJ": {"country": "Djibouti", "region": "Africa"},
    "DK": {"country": "Denmark", "region": "Europe"},
    "DM": {"country": "Dominica", "region": "Americas"},
    "DO": {"country": "Dominican Republic", "region": "Americas"},
    "DZ": {"country": "Algeria", "region": "Africa"},
    "EC": {"country": "Ecuador", "region": "Americas"},
    "EE": {"country": "Estonia", "region": "Europe"},
    "EG": {"country": "Egypt", "region": "Africa"},
    "EH": {"country": "Western Sahara", "region": "Africa"},
    "ER": {"country": "Eritrea", "region": "Africa"},
    "ES": {"country": "Spain", "region": "Europe"},
    "ET": {"country": "Ethiopia", "region": "Africa"},
    "FI": {"country": "Finland", "region": "Europe"},
    "FJ": {"country": "Fiji", "region": "Oceania"},
    "FK": {"country": "Falkland Islands (Malvinas)", "region": "Americas"},
    "FM": {"country": "Micronesia (Federated States of)", "region": "Oceania"},
    "FO": {"country": "Faroe Islands", "region": "Europe"},
    "FR": {"country": "France", "region": "Europe"},
    "GA": {"country": "Gabon", "region": "Africa"},
    "GB": {
      "country": "United Kingdom of Great Britain and Northern Ireland",
      "region": "Europe"
    },
    "GD": {"country": "Grenada", "region": "Americas"},
    "GE": {"country": "Georgia", "region": "Asia"},
    "GF": {"country": "French Guiana", "region": "Americas"},
    "GG": {"country": "Guernsey", "region": "Europe"},
    "GH": {"country": "Ghana", "region": "Africa"},
    "GI": {"country": "Gibraltar", "region": "Europe"},
    "GL": {"country": "Greenland", "region": "Americas"},
    "GM": {"country": "Gambia", "region": "Africa"},
    "GN": {"country": "Guinea", "region": "Africa"},
    "GP": {"country": "Guadeloupe", "region": "Americas"},
    "GQ": {"country": "Equatorial Guinea", "region": "Africa"},
    "GR": {"country": "Greece", "region": "Europe"},
    "GS": {
      "country": "South Georgia and the South Sandwich Islands",
      "region": "Americas"
    },
    "GT": {"country": "Guatemala", "region": "Americas"},
    "GU": {"country": "Guam", "region": "Oceania"},
    "GW": {"country": "Guinea-Bissau", "region": "Africa"},
    "GY": {"country": "Guyana", "region": "Americas"},
    "HK": {"country": "Hong Kong", "region": "Asia"},
    "HM": {"country": "Heard Island and McDonald Islands", "region": "Oceania"},
    "HN": {"country": "Honduras", "region": "Americas"},
    "HR": {"country": "Croatia", "region": "Europe"},
    "HT": {"country": "Haiti", "region": "Americas"},
    "HU": {"country": "Hungary", "region": "Europe"},
    "ID": {"country": "Indonesia", "region": "Asia"},
    "IE": {"country": "Ireland", "region": "Europe"},
    "IL": {"country": "Israel", "region": "Asia"},
    "IM": {"country": "Isle of Man", "region": "Europe"},
    "IN": {"country": "India", "region": "Asia"},
    "IO": {"country": "British Indian Ocean Territory", "region": "Africa"},
    "IQ": {"country": "Iraq", "region": "Asia"},
    "IR": {"country": "Iran (Islamic Republic of)", "region": "Asia"},
    "IS": {"country": "Iceland", "region": "Europe"},
    "IT": {"country": "Italy", "region": "Europe"},
    "JE": {"country": "Jersey", "region": "Europe"},
    "JM": {"country": "Jamaica", "region": "Americas"},
    "JO": {"country": "Jordan", "region": "Asia"},
    "JP": {"country": "Japan", "region": "Asia"},
    "KE": {"country": "Kenya", "region": "Africa"},
    "KG": {"country": "Kyrgyzstan", "region": "Asia"},
    "KH": {"country": "Cambodia", "region": "Asia"},
    "KI": {"country": "Kiribati", "region": "Oceania"},
    "KM": {"country": "Comoros", "region": "Africa"},
    "KN": {"country": "Saint Kitts and Nevis", "region": "Americas"},
    "KP": {
      "country": "Korea (Democratic People's Republic of)",
      "region": "Asia"
    },
    "KR": {"country": "Korea, Republic of", "region": "Asia"},
    "KW": {"country": "Kuwait", "region": "Asia"},
    "KY": {"country": "Cayman Islands", "region": "Americas"},
    "KZ": {"country": "Kazakhstan", "region": "Asia"},
    "LA": {"country": "Lao People's Democratic Republic", "region": "Asia"},
    "LB": {"country": "Lebanon", "region": "Asia"},
    "LC": {"country": "Saint Lucia", "region": "Americas"},
    "LI": {"country": "Liechtenstein", "region": "Europe"},
    "LK": {"country": "Sri Lanka", "region": "Asia"},
    "LR": {"country": "Liberia", "region": "Africa"},
    "LS": {"country": "Lesotho", "region": "Africa"},
    "LT": {"country": "Lithuania", "region": "Europe"},
    "LU": {"country": "Luxembourg", "region": "Europe"},
    "LV": {"country": "Latvia", "region": "Europe"},
    "LY": {"country": "Libya", "region": "Africa"},
    "MA": {"country": "Morocco", "region": "Africa"},
    "MC": {"country": "Monaco", "region": "Europe"},
    "MD": {"country": "Moldova, Republic of", "region": "Europe"},
    "ME": {"country": "Montenegro", "region": "Europe"},
    "MF": {"country": "Saint Martin (French part)", "region": "Americas"},
    "MG": {"country": "Madagascar", "region": "Africa"},
    "MH": {"country": "Marshall Islands", "region": "Oceania"},
    "MK": {"country": "North Macedonia", "region": "Europe"},
    "ML": {"country": "Mali", "region": "Africa"},
    "MM": {"country": "Myanmar", "region": "Asia"},
    "MN": {"country": "Mongolia", "region": "Asia"},
    "MO": {"country": "Macao", "region": "Asia"},
    "MP": {"country": "Northern Mariana Islands", "region": "Oceania"},
    "MQ": {"country": "Martinique", "region": "Americas"},
    "MR": {"country": "Mauritania", "region": "Africa"},
    "MS": {"country": "Montserrat", "region": "Americas"},
    "MT": {"country": "Malta", "region": "Europe"},
    "MU": {"country": "Mauritius", "region": "Africa"},
    "MV": {"country": "Maldives", "region": "Asia"},
    "MW": {"country": "Malawi", "region": "Africa"},
    "MX": {"country": "Mexico", "region": "Americas"},
    "MY": {"country": "Malaysia", "region": "Asia"},
    "MZ": {"country": "Mozambique", "region": "Africa"},
    "NA": {"country": "Namibia", "region": "Africa"},
    "NC": {"country": "New Caledonia", "region": "Oceania"},
    "NE": {"country": "Niger", "region": "Africa"},
    "NF": {"country": "Norfolk Island", "region": "Oceania"},
    "NG": {"country": "Nigeria", "region": "Africa"},
    "NI": {"country": "Nicaragua", "region": "Americas"},
    "NL": {"country": "Netherlands", "region": "Europe"},
    "NO": {"country": "Norway", "region": "Europe"},
    "NP": {"country": "Nepal", "region": "Asia"},
    "NR": {"country": "Nauru", "region": "Oceania"},
    "NU": {"country": "Niue", "region": "Oceania"},
    "NZ": {"country": "New Zealand", "region": "Oceania"},
    "OM": {"country": "Oman", "region": "Asia"},
    "PA": {"country": "Panama", "region": "Americas"},
    "PE": {"country": "Peru", "region": "Americas"},
    "PF": {"country": "French Polynesia", "region": "Oceania"},
    "PG": {"country": "Papua New Guinea", "region": "Oceania"},
    "PH": {"country": "Philippines", "region": "Asia"},
    "PK": {"country": "Pakistan", "region": "Asia"},
    "PL": {"country": "Poland", "region": "Europe"},
    "PM": {"country": "Saint Pierre and Miquelon", "region": "Americas"},
    "PN": {"country": "Pitcairn", "region": "Oceania"},
    "PR": {"country": "Puerto Rico", "region": "Americas"},
    "PS": {"country": "Palestine, State of", "region": "Asia"},
    "PT": {"country": "Portugal", "region": "Europe"},
    "PW": {"country": "Palau", "region": "Oceania"},
    "PY": {"country": "Paraguay", "region": "Americas"},
    "QA": {"country": "Qatar", "region": "Asia"},
    "RE": {"country": "R\u00e9union", "region": "Africa"},
    "RO": {"country": "Romania", "region": "Europe"},
    "RS": {"country": "Serbia", "region": "Europe"},
    "RU": {"country": "Russian Federation", "region": "Europe"},
    "RW": {"country": "Rwanda", "region": "Africa"},
    "SA": {"country": "Saudi Arabia", "region": "Asia"},
    "SB": {"country": "Solomon Islands", "region": "Oceania"},
    "SC": {"country": "Seychelles", "region": "Africa"},
    "SD": {"country": "Sudan", "region": "Africa"},
    "SE": {"country": "Sweden", "region": "Europe"},
    "SG": {"country": "Singapore", "region": "Asia"},
    "SH": {
      "country": "Saint Helena, Ascension and Tristan da Cunha",
      "region": "Africa"
    },
    "SI": {"country": "Slovenia", "region": "Europe"},
    "SJ": {"country": "Svalbard and Jan Mayen", "region": "Europe"},
    "SK": {"country": "Slovakia", "region": "Europe"},
    "SL": {"country": "Sierra Leone", "region": "Africa"},
    "SM": {"country": "San Marino", "region": "Europe"},
    "SN": {"country": "Senegal", "region": "Africa"},
    "SO": {"country": "Somalia", "region": "Africa"},
    "SR": {"country": "Suriname", "region": "Americas"},
    "SS": {"country": "South Sudan", "region": "Africa"},
    "ST": {"country": "Sao Tome and Principe", "region": "Africa"},
    "SV": {"country": "El Salvador", "region": "Americas"},
    "SX": {"country": "Sint Maarten (Dutch part)", "region": "Americas"},
    "SY": {"country": "Syrian Arab Republic", "region": "Asia"},
    "SZ": {"country": "Eswatini", "region": "Africa"},
    "TC": {"country": "Turks and Caicos Islands", "region": "Americas"},
    "TD": {"country": "Chad", "region": "Africa"},
    "TF": {"country": "French Southern Territories", "region": "Africa"},
    "TG": {"country": "Togo", "region": "Africa"},
    "TH": {"country": "Thailand", "region": "Asia"},
    "TJ": {"country": "Tajikistan", "region": "Asia"},
    "TK": {"country": "Tokelau", "region": "Oceania"},
    "TL": {"country": "Timor-Leste", "region": "Asia"},
    "TM": {"country": "Turkmenistan", "region": "Asia"},
    "TN": {"country": "Tunisia", "region": "Africa"},
    "TO": {"country": "Tonga", "region": "Oceania"},
    "TR": {"country": "Turkey", "region": "Asia"},
    "TT": {"country": "Trinidad and Tobago", "region": "Americas"},
    "TV": {"country": "Tuvalu", "region": "Oceania"},
    "TW": {"country": "Taiwan, Province of China", "region": "Asia"},
    "TZ": {"country": "Tanzania, United Republic of", "region": "Africa"},
    "UA": {"country": "Ukraine", "region": "Europe"},
    "UG": {"country": "Uganda", "region": "Africa"},
    "UM": {
      "country": "United States Minor Outlying Islands",
      "region": "Oceania"
    },
    "US": {"country": "United States of America", "region": "Americas"},
    "UY": {"country": "Uruguay", "region": "Americas"},
    "UZ": {"country": "Uzbekistan", "region": "Asia"},
    "VA": {"country": "Holy See", "region": "Europe"},
    "VC": {"country": "Saint Vincent and the Grenadines", "region": "Americas"},
    "VE": {
      "country": "Venezuela (Bolivarian Republic of)",
      "region": "Americas"
    },
    "VG": {"country": "Virgin Islands (British)", "region": "Americas"},
    "VI": {"country": "Virgin Islands (U.S.)", "region": "Americas"},
    "VN": {"country": "Viet Nam", "region": "Asia"},
    "VU": {"country": "Vanuatu", "region": "Oceania"},
    "WF": {"country": "Wallis and Futuna", "region": "Oceania"},
    "WS": {"country": "Samoa", "region": "Oceania"},
    "YE": {"country": "Yemen", "region": "Asia"},
    "YT": {"country": "Mayotte", "region": "Africa"},
    "ZA": {"country": "South Africa", "region": "Africa"},
    "ZM": {"country": "Zambia", "region": "Africa"},
    "ZW": {"country": "Zimbabwe", "region": "Africa"}
  }
};
